/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.guessinggamegrafico;

/**
 *
 * @author GUILHERMEDIASVILLANO
 */
public class Grafico extends javax.swing.JFrame {

    /**
     * Creates new form Grafico
     */
    public Grafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome = new javax.swing.JLabel();
        describe = new javax.swing.JLabel();
        userNumber = new javax.swing.JTextField();
        confirmaNumber = new javax.swing.JButton();
        resposta = new javax.swing.JLabel();
        dica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcome.setText("bem-vindo ao guessing Game!!");

        describe.setText("Digite um numero do 1 ao 100");

        userNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNumberActionPerformed(evt);
            }
        });

        confirmaNumber.setText("Confirmar");
        confirmaNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaNumberActionPerformed(evt);
            }
        });

        resposta.setText("Resposta:");

        dica.setText("dica: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(describe)
                    .addComponent(welcome))
                .addGap(249, 249, 249))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(resposta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmaNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(dica)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(describe)
                .addGap(42, 42, 42)
                .addComponent(userNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(confirmaNumber)
                .addGap(50, 50, 50)
                .addComponent(resposta)
                .addGap(43, 43, 43)
                .addComponent(dica)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNumberActionPerformed

    private void confirmaNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaNumberActionPerformed
        nNumber();
    }//GEN-LAST:event_confirmaNumberActionPerformed
    guessingNumber guessingNumber = new guessingNumber();
   // GuessValidator validar = new GuessValidator();

   String ajuda = "";
   
    private void nNumber() {
        String mudarResposta = "";
        int number = guessingNumber.getNumber();
        String respota = userNumber.getText();
        int numberResposta = Integer.parseInt(respota);

        if (number == numberResposta) {
            mudarResposta += " você acertou o numero parabens!!";
        }
        if (number != numberResposta) {
            mudarResposta += " Você errou o numero. tente novamente";
            //validar.validateGuess(numberResposta, number);
            
            if(number > numberResposta){
                ajuda = "dica: palpite muito baixo";
            } 
            
            if(number < numberResposta){
                ajuda = "dica: palpite muito alto";
            }
            
        }

        System.out.println(number);
        resposta.setText(mudarResposta);
        dica.setText(ajuda);

    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmaNumber;
    private javax.swing.JLabel describe;
    private javax.swing.JLabel dica;
    private javax.swing.JLabel resposta;
    private javax.swing.JTextField userNumber;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
